<?php
$block = new \app\modules\Codnitive\Core\blocks\Template;
?>
<div class="home2"></div>
<?= $breadcrumbs ?>

<div class="clearfix"></div>
<section class="mb-0 mt-2">
    <div class="container">
        <div class="container my-5 text-center">
            <div class="alert alert-success"><span class="fa fa-check"></span>
            <?= __('sepmicro', 'You will be redirect to Saman payment gateway in few second, please be patient...') ?>
            <?php $form = $block->beginForm([
                'action' => 'https://sep.shaparak.ir/payment.aspx',
                'options' => [
                    'method' => 'post',
                    'id' => 'sep_micro_redirect_form'
                ]
            ]); ?>
            <?php /*<?= $block->html()->getHiddenField($form, $formModel, 'Amount'); ?>
            <?= $block->html()->getHiddenField($form, $formModel, 'MID'); ?>
            <?= $block->html()->getHiddenField($form, $formModel, 'ResNum'); ?>*/ ?>
            <?= $block->html()->getHiddenField($form, $formModel, 'Token'); ?>
            <?= $block->html()->getHiddenField($form, $formModel, 'RedirectURL'); ?>
            <?php $block->endForm(); ?>
            <script type="text/javascript">
            $(document).ready(function () {
                $('#sep_micro_redirect_form').submit();
            });
            </script>
            </div>
        </div>
    </div>
</section>
<hr>
