<?php 
$persianDate = new \app\modules\Codnitive\Calendar\models\Persian;
?>
<?php if (!empty($params)): ?>
<div class="container search-info box-result d-flex flex-row flex-lg-row flex-md-row flex-sm-row flex-columnjustify-content-between justify-content-md-between justify-content-sm-between gray-back  align-items-center align-items-md-cente align-items-sm-center">
    <div class="p-3 d-flex flex-wrap">
        <div class="d-flex align-items-center align-items-center justify-content-center item-search box-bus ">
            <span class="icon-bus"></span>
        </div>
        <span class="res-search d-inline-flex mr-2 align-items-center justify-content-center">
            <?= __('bus', 'Bus ticket from {origin_name} to {destination_name}', $params) ?>
        </span>
    </div>
    <div class="p-3 d-inline-flexalign-items-center justify-content-center">
        <span class="d-inline-flex mr-2 align-items-center justify-content-center"><?= __('bus', 'Date') ?>: </span>
        <span class="date-result-bus d-inline-flex mr-2 align-items-center justify-content-center"><?= $persianDate->getDate($params['departing']) ?></span>
    </div>
    <div class="p-3 d-flex"><?= __('bus', 'Search Result') ?>:&nbsp;<span class="search-result-count">-</span><?= __('bus', 'Item(s)') ?></div>
    <div class="p-3 d-flex search-again" data-toggle="collapse" href="#bus_search_again_form" role="button" aria-expanded="false" aria-controls="bus_search_again_form">
        <?= __('template', 'Search Again') ?><i class="fa fa-search mr-2"></i>
    </div>
</div>
<div id="bus_search_again_form" class="collapse container">
    <div class="bilit-serach-box pt-5">
        <div class="tab-bus">
            <?= $this->render('/templates/index/search/bus.form.phtml'); ?>
        </div>
    </div>
</div>
<?php endif; ?>
