<div class="about">
    <div class="container">
        <div class="row row-lg-eq-height">
            <div class="col">
                <div class="text-center mb-3">
                    <h2 class=""><img src="<?= tools()->getImageUrl('logo_blue.svg') ?>" alt="Bilit.com" style="width: 150px; height: 150px;"></h2>
                </div>
            </div>
            <div class="about-text  mb-3">
<p>بیمه از مهم‌ترین مواردی است که هنگام سفر باعث اطمینان و آرامش خاطر فرد می‌شود. حوادث و اتفاقات غیرقابل پیش‌بینی هستند و ممکن است زمانی رخ بدهند که اصلا انتظار نداریم. به همین دلیل بیمه مسافرتی بهترین گزینه‌ برای محافظت از خود در طول سفر است و هرچقدر هزینه‌های سفر را افزایش دهد ازرش هزینه‌کردن دارد. مسافران در طول سفر می‌توانند با تکیه بر بیمه هزینه‌های درمانی یا اتفاقات ناگهانی را جبران کنند. بیمه مسافرتی مخصوص کسانی است که قصد مسافرت به خارج از کشور دارند و اعتبار آن فقط در خارج از کشور است. بیمه‌نامه‌های مختلف با هم فرق دارند و سطح پوشش آن‌ها با هم متفاوت است.</p>
            <p>بیمه مسافرتی عبارت است از پوشش صدمات بدنی و بیماری بیمه شده که پس از شروع سفر به خارج بروز نموده یا عارضه ناگهانی و غیرقابل پیش‌بینی که ابتلا به آن یا آغاز آن پس از شروع سفر به خارج بوده و موجب درخواست امداد از طرف بیمه شده یا نمایندگان وی شود. </p>
            </div>
        </div>
    </div>
</div>

<section class="benefit_area ">
    <div class="container">
        <div class="row  text-center d-flex flex-row align-items-center justify-content-around">
            <div class="col-md-3 col-sm-6 service_col d-flex justify-content-around ">
                <div class="service text-center trans_200">
                    <div class="service_icon flex-fill d-flex align-items-center justify-content-center
                    "><span class="icon-ticket color"></span></div>
                    <div class="service_title trans_200">جستجوی بلیط</div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 service_col">
                <div class="service text-center trans_200">
                    <div class="service_icon flex-fill d-flex align-items-center justify-content-center"><span class="icon-ticket-select color"></span></div>
                    <div class="service_title trans_200">انتخاب بلیط</div>

                </div>
            </div>
            <div class="col-md-3 col-sm-6 service_col">
                <div class="service text-center trans_200">
                    <div class="service_icon flex-fill d-flex align-items-center justify-content-center"><span class="icon-information color"></span></div>
                    <div class="service_title trans_200">تکمیل مشخصات</div>

                </div>
            </div>
            <div class="col-md-3 col-sm-6 service_col">
                <div class="service text-center trans_200">
                    <div class="service_icon flex-fill d-flex align-items-center justify-content-center"><span class="fa fa-shopping-cart color"></span></div>
                    <div class="service_title trans_200">خرید و پرداخت</div>
            </div>
        </div>
    </div>
    </div>
</section>

<!--================Creative Feature Area =================-->
<section class="bus_feature_area py-5 mt-5">
    <div class="container">
    
        <div class="bus_feature p_100">
            <div class="row">
                <div class="col-lg-6">
                    <div class="d_feature_text">
                        <div class="main_title color mb-3">
                            <h2 class="color">خدماتی که بیمه‌های مسافرتی تحت پوشش قرار می‌دهند</h2>
                        </div>
                    <ol class="bus-feature-item mt-5 ml-4 mr-0">
<li>فوریت‌های پزشکی و معالجات درمانی</li>
<li>هزینه‌های دندان‌پزشکی</li>
<li>لغو سفر</li>
<li>مرگ تصادفی</li>
<li>گم کردن یا به سرقت رفتن اموال و اسباب سفر</li>
<li>ابلاغ مقامات رسمی به عنوان شاهد</li>
<li>فراخوانده شدن به خدمت اگر عضو نیروهای مسلح یا سازمان‌های امنیتی یا دفاعی باشید.  </li>
<li>حواله وجه نقد</li>
<li>ارسال وجه‌الضمان</li>
</ol>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="d_feature_img">
                        <img src="<?= tools()->getImageUrl('default-insurance-companies-5.jpg') ?>">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
