<?php 
/**
 * Main search form for searching insurance plans for specific country and for
 * a specific duration of time
 */

// use app\modules\Codnitive\Insurance\models\Travis;

$searchModel = new \app\modules\Codnitive\Insurance\models\SearchForm;
$block  = new \app\modules\Codnitive\Insurance\blocks\SearchForm;
$block->registerAssets($this, 'Insurance', 'Insurance');

$block->html()->setNameSpace('insurance');
?>

<?php //if ($this->beginCache('insurance_search_form', ['duration' => 20])): ?>
<div id="insurance-content" class="row search-menu">
    <div class="col-md-12 col-lg-12 col-md-offset-2 col-lg-offset-2">
        <?php $form = $block->beginForm([
            'action'  => $block->getActionUrl(),
            'id'      => 'insurance_form',
            'method'  => 'GET',
            'options' => ['autocomplete' => 'off'],
            // 'validateOnBlur'=>false,
            // 'fieldConfig' => [
            //     'template'=>"{input}\n{error}",
            //     //     'template' => "{label}\n<div class=\"col-lg-9\">{input}</div>\n<div class=\"col-sm-offset-3 col-lg-9\">{error}\n{hint}</div>",
            //     //     'labelOptions' => ['class' => 'col-lg-3 control-label'],
            // ],
            // 'enableAjaxValidation' => true,
            // 'enableClientValidation' => false,
        ]); ?>
            <?php /*<?= tools()->getCsrfInput() ?>*/ ?>
            <?= $block->html()->getHiddenField($form, $searchModel, 'country_name'); ?>
            <div class="row">
                <?= $block->html()->getDropdownList(
                        $form, 
                        $searchModel, 
                        'country', 
                        // $block->getCountriesArray(),
                        [],
                        [
                            'form_group_class' => 'col-sm-6 col-md-3',
                            'prompt' => __('insurance', 'Destination Country'),
                            'remove_label' => true,
                            'icon' => 'fa fa-map-marker'
                        ],
                        $this
                    )
                    ->label(__('insurance', 'Destination Country')) 
                ?>
                <?= $block->html()->getDropdownList(
                        $form, 
                        $searchModel, 
                        'duration', 
                        // $block->getDurationsArray(),
                        [],
                        [
                            'form_group_class' => 'col-sm-6 col-md-3',
                            'prompt' => __('insurance', 'Duration of Stay'),
                            'remove_label' => true,
                            'icon' => 'fa fa-info'
                        ],
                        $this
                    )
                    ->label(__('insurance', 'Duration of Stay')) 
                ?>
                <?= $block->html()->getField(
                        $form, 
                        $searchModel, 
                        'age', 
                        'fa fa-calendar',
                        '',
                        ['form_group_class' => 'col-sm-6 col-md-3', 'remove_label' => true]
                    )->label(__('insurance', 'Age')) 
                ?>

                <div class="col-xs-12 col-sm-6 col-md-3">
                <?= $block->html()->submitButton(
                    __('insurance', 'Get Plans'), 
                    [
                        'class' => 'btn mj-btn-orange btn-purple',
                        'id' => 'insurance-submit',
                    ]
                ) ?>
                </div>
            </div>
        <?php $block->endForm(); ?>
    </div>
</div>
<?php //$this->endCache() ?>
<?php //endif; ?>
