<?php 
/**
 * Main search form for searching insurance plans for specific country and for
 * a specific duration of time
 */

$searchModel = new \app\modules\Codnitive\Bus\models\SearchForm;
$block  = new \app\modules\Codnitive\Bus\blocks\SearchForm;
$block->registerAssets($this, 'Bus', 'Bus');

$block->html()->setNameSpace('bus');
?>

<div class="row search-menu">
    <div class="col-md-12 col-lg-12 col-md-offset-2 col-lg-offset-2">
        <?php $form = $block->beginForm([
            'action'  => [$block->getActionUrl()],
            'id'      => 'bus_form',
            'method'  => 'GET',
            'options' => ['autocomplete' => 'off'],
            // 'validateOnBlur'=>false,
            // 'fieldConfig' => [
            //     'template'=>"{input}\n{error}",
            //     //     'template' => "{label}\n<div class=\"col-lg-9\">{input}</div>\n<div class=\"col-sm-offset-3 col-lg-9\">{error}\n{hint}</div>",
            //     //     'labelOptions' => ['class' => 'col-lg-3 control-label'],
            // ],
            // 'enableAjaxValidation' => true,
            // 'enableClientValidation' => false,
        ]); ?>
            <div class="row">
                <?= $block->html()->getHiddenField($form, $searchModel, 'origin_name'); ?>
                <?= $block->html()->getDropdownList(
                        $form, 
                        $searchModel, 
                        'origin', 
                        // $block->getOriginCities(),
                        [],
                        [
                            'form_group_class' => 'col-sm-6 col-md-3',
                            'prompt' => __('bus', 'Origin'),
                            'remove_label' => true,
                            'icon' => 'fa fa-map-marker'
                        ],
                        $this
                    )
                    ->label(__('bus', 'Origin')) 
                ?>
                
                <?= $block->html()->getHiddenField($form, $searchModel, 'destination_name'); ?>
                <?= $block->html()->getDropdownList(
                        $form, 
                        $searchModel, 
                        'destination', 
                        // $block->getDestinationCities(),
                        [],
                        [
                            'form_group_class' => 'col-sm-6 col-md-3',
                            'prompt' => __('bus', 'Destination'),
                            'remove_label' => true,
                            'icon' => 'fa fa-map-marker'
                        ],
                        $this
                    )
                    ->label(__('bus', 'Destination')) 
                ?>
                
                <?= $block->html()->getHiddenField($form, $searchModel, 'departing'); ?>
                <?= $block->html()->getDateField($form, $searchModel, 'departing_persian', $this, [
                        'class'=> 'departing-datepicker',
                        'form_group_class' => 'col-sm-6 col-md-3',
                        /*'form_group_class'  => 'col-12',
                        'col_size'          => 'col-12',*/
                        'remove_label' => true,
                        'icon' => 'fa fa-calendar',
                        // @reference datepicker page: https://github.com/Mds92/MD.BootstrapPersianDateTimePicker
                        'date_options' => [
                            'targetDateSelector' => '#bus-departing',
                            // 'targetTextSelector' => '#bus-departing',
                            'dateFormat' => 'yyyy-MM-dd',
                            // 'textFormat' => 'yyyy-MM-dd',
                            // 'isGregorian' => false,
                            'disableBeforeToday' => true,
                            'monthsToShow' => [0, 1],
                            // 'rangeSelector' => true,
                            'englishNumber' => true
                        ]
                    ])
                    ->label(__('bus', 'Departing Date')) 
                ?>
                <?php /*<script type="text/javascript">
                $(document).ready(function () {
                    $('input.departing-datepicker').Zebra_DatePicker(
                        JSON.parse('<?= $block->html()->datepickerConfig() ?>')
                    );
                });
                </script>
                <?= $block->html()->getField(
                    $form, 
                    $searchModel, 
                    'passengers', 
                    ['form_group_class' => 'col-sm-6 col-md-3']
                )->label(__('bus', 'Passengers')
                ) ?>*/ ?>
                <div class="col-xs-12 col-sm-6 col-md-3">
                <?= $block->html()->submitButton(
                    __('bus', 'Find Bus'), 
                    [
                        'class' => 'btn mj-btn-orange btn-pink',
                        'id' => 'bus-submit',
                    ]
                ) ?>
                </div>
            </div>
        <?php $block->endForm(); ?>
    </div>
</div>
<?php //$this->endCache() ?>
<?php //endif; ?>
