<div class="passengers-supervisor-wrapper">
    <div class="d-flex flex-row flex-lg-row flex-md-row flex-sm-row align-items-center justify-content-between flex-column p-3">
        <h5 class="d-flex">
            <i class="fa fa-info-circle pink mr-2 ml-0"></i>
            <?= __('bus', 'You reserved {passengers_count} seat(s), please enter the supervisor info.', ['passengers_count' => $passengersCount]) ?>
        </h5>
        <?php /*
        <div class="d-flex ">
            <button type="button" data-toggle="modal" data-target="#box-history-modal" class="  btn submit_btn2 ">
                <i class="fa fa-user blue-i mr-2 ml-0 color-i"></i><?= __('template', 'Passenger Book') ?>
            </button>
        </div>*/ ?>
    </div>

    <div class="supervisor-info row p-2">
        <?= $block->html()->getField($form, $model, "email", '', '', ['form_group_class' => 'col-sm-6 col-md-4', 'class' => 'firstname']); ?>
        <?= $block->html()->getField($form, $model, "firstname", '', '', ['form_group_class' => 'col-sm-6 col-md-4', 'class' => 'firstname']); ?>
        <?= $block->html()->getField($form, $model, "lastname", '', '', ['form_group_class' => 'col-sm-6 col-md-4', 'class' => 'lastname']); ?>
        <?php /*<?= $block->html()->getDropdownList($form, $model, "gender", tools()->getOptionsArray('Core', 'Gender'), ['form_group_class' => 'col-sm-6 col-md-3', 'class' => 'gender-drop']) ?>*/ ?>
        <?= $block->html()->getDropdownList(
                    $form, 
                    $model, 
                    'gender', 
                    tools()->getOptionsArray('Core', 'Gender'),
                    [
                        'form_group_class' => 'col-sm-6 col-md-4',
                        'prompt' => __('bus', 'Gender'),
                        'live_search' => 'false'
                    ],
                    $this
                )
                ->label(__('bus', 'Gender')) 
            ?>
        <?= $block->html()->getField($form, $model, "cellphone", '', '', ['form_group_class' => 'col-sm-6 col-md-4', 'class' => 'cell-phone']); ?>
    </div>
</div>

<div class="info-box clearfix mt-3">
    <hr>
    <a href="<?= $block->getBackUrl() ?>" class="col-sm-2 col-xs-12 float-left back-link force-color-default"><?= __('template', 'Back') ?></a>
</div>

<?php /*
<div class="modal fade" id="bus-terms" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title color" id="exampleModalLongTitle"><?= __('bus', 'Bus Terms') ?></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <?= $this->render('@app/modules/Codnitive/Cms/views/templates/terms/bus_modal.phtml') ?>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary btn-pink col-2" data-dismiss="modal"><?= __('template', 'I Agree') ?></button>
    </div>
  </div>
</div>
</div>*/ ?>
