<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\modules\Codnitive\Setup\models\Database */

// use yii\helpers\Html;
// use yii\bootstrap\ActiveForm;

// use app\modules\Codnitive\Template\assets\Home;
// Home::register($this);
$block = new \app\modules\Codnitive\Core\blocks\Template;
$block->registerAssets($this, 'Template', 'ZebraDatepicker');

$this->title = __('template', 'Bilit | Home Page');
?>

