<?php
$block = new \app\modules\Codnitive\Core\blocks\Template;

$this->title = __('template', 'Youwe Backend Test');
?>

<div class="page-header header-filter">
    <div class="squares square1"></div>
    <div class="squares square2"></div>
    <div class="squares square3"></div>
    <div class="squares square4"></div>
    <div class="squares square5"></div>
    <div class="squares square6"></div>
    <div class="squares square7"></div>
    <div class="container">
    <div class="content-center brand">
        <h1 class="h1-seo">YOUWE</h1>
        <h3>A backend test to find best developers, Poker chance and String Graph.</h3>
    </div>
    </div>
</div>
<section id="scroll_down" class="scroll">
    <a href="#projects_list"><span></span><span></span><span></span></a>
</section>
<?= $this->render('home/projects.phtml') ?>
