<!-- Example DataTables Card-->
<div class="card mb-3 recent-received-orders orders-grid">
    <div class="d-flex flex-row justify-content-between p-3 align-items-center bd-bottom">
        <span class=""> <?= __('account', 'Recent Orders') ?></span>
        <i class="fas fa-list blue"></i>
    </div>
    <div class="card-body">
        <div class="table-responsive py-4 px-2 orders-grid-table">
            <?= $ordersGrid->toHtml(); ?>
        </div>
    </div>
</div>