<?php
use app\modules\Codnitive\Core\helpers\Html;
$this->title = __('wallet', 'My Wallet');
?>

<div class="card mb-3 mt-5">
    <div class="d-flex flex-row justify-content-between p-3 align-items-center bd-bottom">
        <span class=""></i> <?= __('wallet', 'Recent Transactions') ?></span>
        <i class="fas fa-list blue"></i>
    </div>
    <div class="card-body">
        <div class="table-responsive py-4 px-2 data-table grid">
            <?= Html::getGridPerPage($transactionGrid->showResetFilterButton(), tools()->getPerPageSize()); ?>
            <?= $transactionGrid->toHtml(); ?>
        </div>
    </div>
</div>
