<?php
$this->title = __('account', 'Dashboard');
?>

<div class="card-body-account">
    <h4><?= __('template', 'Account') ?></h4>
    <div class="right-content">
        <div class="text-center mt-4">
            <div class="d-flex flex-row justify-content-between align-items-stretch">
                <?= $this->render('dashboard/user_info.phtml', ['userIdentity' => $userIdentity]) ?>
                <?= $this->render('dashboard/wallet_info.phtml', ['userIdentity' => $userIdentity, 'formModel' => $formModel]) ?>
            </div>
            <div class="clearfix "></div>
        </div>
        <div class="box-info mt-4">
            <?= $this->render('dashboard/recent_received_orders.phtml', ['ordersGrid' => $ordersGrid]); ?>
        </div>
    </div>
</div>
