<!-- The Modal -->
<div class="modal" id="modal_box" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title"><?= $title ?></h4>
        <?php /*<button type="button" class="close" data-dismiss="modal">&times;</button>*/ ?>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <?= $body ?>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <?php /*<button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>*/ ?>
        <?= $footer ?>
      </div>

    </div>
  </div>
</div>
