<div class="quick-log-in d-flex  flex-column mt-3 p-3">
    <h5 class="d-flex mb-4"><i class="fa fa-info-circle pink ml-2"></i><?= __('template', 'You can login to your account if you have or create a new account.') ?></h5>
    <div class="d-flex  justify-content-center">
        <div class=" d-flex p-3">
             <a href="<?= tools()->getUrl('user/login', ['prev_url' => app()->request->url]) ?>" class="btn submit_btn2 ">
                 <i class="fas fa-sign-in-alt mr-2 ml-0 color-i trans-icon"></i></i><?= __('template', 'Login') ?> 
            </a>
        </div>
        <div class="d-flex  p-3">
             <a  href="<?= tools()->getUrl('user/register', ['prev_url' => app()->request->url]) ?>" class="btn submit_btn2 ">
                 <i class="fa fa-user-plus mr-2 ml-0 color-i"></i><?= __('template', 'Sign Up') ?> 
            </a>
        </div>
    </div>
</div>
<hr>
