<div id="back-to-top"></div>
<script>
$(document).ready(function() {
	"use strict";
	$('#back-to-top').on('click', function(){
	$('body,html').animate({
		scrollTop: 0
	}, 600);
});
///////////////////////////
// On Scroll
	$(window).on('scroll', function() {
		var wScroll = $(this).scrollTop();

		// Fixed nav
		wScroll > 1 ? $('#nav').addClass('fixed-nav') : $('#nav').removeClass('fixed-nav');

		// Back To Top Appear
		wScroll > 300 ? $('#back-to-top').fadeIn() : $('#back-to-top').fadeOut();
	});
});
///////////////////////////
</script>
