<form id="checkout_payment_methods" action="<?= tools()->getUrl('insurance/plans/payment') ?>" method="post">
    <?= tools()->getCsrfInput() ?>
    <div class="info-box__discount info-box__item">
        <?= $this->render('@app/modules/Codnitive/Checkout/views/templates/payments.phtml') ?>  
        <hr>
        <div class="row bill-box justify-content-center p-2 mt-4 grand-total-wrapper">
            <div class="info-box__price info-box__item grand-total col-12 hidden">
                <div class="item-discount ">
                    <span class="item-discount__label"><?= __('template', 'Grand Total') ?>:&emsp13;</span>
                    <span class="price__amount-price credit-total"><?= $block->getGrandTotal($allInsurances) ?></span>
                </div>
            </div>
            <div class="info-box__price info-box__item used-credit-total col-12 hidden">
                <div class="item-discount  ">
                    <span class="item-discount__label"><?= __('template', 'Used Credit') ?>:&emsp13;</span>
                    <span class="price__amount-price credit-total-price"></span>
                </div>
            </div>
            <div class="info-box__price info-box__item online-payable-grand-total col-12">
                <div class="item-discount  ">
                    <span class="item-discount__label"><?= __('template', 'Payable Total') ?>:&emsp13;</span>
                    <span class="price__amount-price grand-total-price"><?= $block->getGrandTotal($allInsurances) ?></span>
                </div>
            </div>
        </div>  
        <div class="d-flex f mb-3 col-12 mt-3">
            <button type="submit" class="btn btn-purple"><?= __('template', 'Pay') ?></button>
        </div>
    </div>
</form>
