<!-----------------right-section------------------------>
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <?php if (!count($plans)): ?>
        <div class="d-flex flex-column insurance-item gray-back p-5 text-center">
            <?= __('insurance', 'Unfortunately no result found for your search.') ?>
        </div>
    <?php else: ?>
        <div class="right-section">
            <?php $i = 1 ?>
            <?php foreach ($plans as $plan): ?>
            <div class="d-flex flex-column insurance-item">
                <div class="d-flex flex-lg-row flex-md-row flex-sm-row flex-column box-bus-item p-2">
                    <div class="icon d-flex justify-content-center align-items-center">
                        <img src="<?= tools()->getMediaUrl('insurance/saman/logo.png') ?>" alt="<?= __('insurance', 'Saman Insurance - bilit.com') ?>">
                    </div>
                    <div class="col-md-10  flex-column  right-box-bus">
                        <div class="row">
                            <div class="col-10">
                                <div class="Bus-name d-flex mb-3 align-items-center gray"><?= __('insurance', 'Online - All the World Countries') ?></div>
                                <div class="Bus-rout mb-3 d-flex align-items-center"><strong class="route"><?= __('insurance', $plan->title) ?></strong> 
                                    <span class="dash" style="width: 250px;"></span>
                                    <strong class="words route"><?= __('insurance', 'Destination Country') ?> <span><?= __('insurance', $params['country_name']) ?></span></strong>
                                </div>
                                <div class="details-insurance d-flex  align-items-center mb-2">
                                    <a class="btn-more" data-toggle="collapse" data-target="#collapseExample<?= $i ?>" aria-expanded="false"
                                        aria-controls="collapseExample">
                                        <?= __('insurance', 'More Details') ?> <i class="fa fa-caret-down mr-2"></i>
                                    </a>
                                </div>
                            </div>
                            <div class="col-2 d-flex justify-content-center align-items-center"><?= __('insurance', 'Cover Limit {cover_limit}', ['cover_limit' => $plan->coverLimit]) ?></div>
                        </div>
                    </div>

                    <div class="col-md-2 flex-column d-flex align-items-center left-box-bus  align-items-cente">
                        <div class="insurance-price d-flex flex-column align-items-center justify-content-center  mt-4">
                            <p class="mb-2">
                                <span class="price mb-1 d-flex align-items-center d-flex align-items-center " itemprop="price" title="" >
                                    <?= tools()->formatRial($plan->price) ?> <strong class="color-blue"></strong>
                                </span>
                            </p>
                            <a  href="<?= tools()->getUrl('insurance/plans/buy', ['plan_code' => $plan->code, 'plan_title' => $plan->title]) ?>"
                                class="buybtn btn-purple collapsed"><?= __('template', 'Buy') ?></a>
                        </div>
                    </div>
                </div>
                <div class="collapse p-2 collapse-insu" id="collapseExample<?= $i++ ?>">
                    <div class="card card-body">
                        <ol class="p-3">
                            <?php foreach ($plan->covers->TISPlanCoversInfo as $cover): ?>
                            <li class="mb-2" style="border-bottom: 1px dashed #ccc;">
                                <div class="row">
                                    <div class="col-10 my-3"><?= __('insurance', $cover->coverTitle) ?></div>
                                    <div class="col-2 my-3"><?= __('insurance', $cover->planCoverLimit) ?></div>
                                </div>
                            </li>
                            <?php endforeach; ?>
                        </ol>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</div>
