<div class="container box-result d-flex flex-row flex-lg-row flex-md-row flex-sm-row flex-columnjustify-content-between justify-content-md-between justify-content-sm-between gray-back  align-items-center align-items-md-cente align-items-sm-center">
    <div class="p-4 d-flex flex-wrap">
        <div class="d-flex align-items-center align-items-center justify-content-center item-search box-insurance ">
            <span class="icon-insurance"></span>
        </div>
        <span class="res-search d-inline-flex mr-2 align-items-center justify-content-center"><?= __('insurance', 'Traveling Insurance for {country_name}', $params) ?></span>
    </div>
    <div class="p-4 d-inline-flexalign-items-center justify-content-center">
        <span class="d-inline-flex mr-2 align-items-center justify-content-center"><?= __('insurance', 'Duration of Stay') ?>: </span>
        <span class="date-result-bus d-inline-flex mr-1 align-items-center justify-content-center"><?= __('insurance', '{duration} Day(s)', $params) ?></span>
    </div>
    <div class="p-4 d-flex"><?= __('insurance', 'Found items') ?>: <span><?= __('insurance', '{count} Item(s)', ['count' => count($plans)]) ?></span></div>
    <div class="p-3 d-flex search-again" data-toggle="collapse" href="#insurance_search_again_form" role="button" aria-expanded="false" aria-controls="insurance_search_again_form">
        <?= __('template', 'Search Again') ?><i class="fa fa-search mr-2"></i>
    </div>
</div>

<div id="insurance_search_again_form" class="collapse container">
    <div class="bilit-serach-box pt-5">
        <div class="tab-insurance">
            <?= $this->render('/templates/index/search/insurance.form.phtml'); ?>
        </div>
    </div>
</div>
<div class="clearfix"></div>
