<?php
$block  = new \app\modules\Codnitive\Insurance\blocks\Plans\Confirm;
$block->registerAssets($this, 'Insurance', 'Insurance');
?>

<div class="home2"></div>
<?= $breadcrumbs ?>

<div class="bus-check container mb-4 mt-2" id="scroller-anchor-main">
    <div class="d-flex flex-column ">
        <div class="d-flex flex-row">
            <div class="col-md-9 pd-right">
                <div class="d-flex flex-column">
                    <div class="box-shadow ajax-result-wrapper">
                        <div class="loading p-5"><div class="message"><i class="fa fa-spinner rotating"></i><?= __('insurance', 'Trying to register policies, please be patient...') ?></div></div>
                        <script type="text/javascript">
                        $(document).ready(function () {
                            insurance.registerPolicies();
                        });
                        </script>
                    </div>
                </div>
            </div>
            <?= $this->render('/templates/plans/sidebar.phtml', [
                'step' => 'confirm', 
                // 'model' => $model, 
                'block' => $block,
                'data' => $block->getInsuranceData()
            ]) ?>
        </div>
    </div>
</div>
