<div class="home2"></div>
<?= $breadcrumbs ?>
<?php if (!$insurances) return; ?>

<?php 
$paymentInfo = $order->payment_info;
if (tools()->isJson($paymentInfo)) {
    $paymentInfo = \yii\helpers\Json::decode($paymentInfo);
}
$traceNumber = $paymentInfo['trace_number'];
?>
<div class="clearfix"></div>
<section class="mb-0 mt-2">
    <div class="container">
        <div class="text-center">
            <h2 class="my-5"><?= __('template', 'Thank you for your order!') ?></h2>
            <p><h4><strong><?= __('template', 'Order #: ') ?></strong><?= $order->getOrderNumber() ?></h4></p>
            <p><h4><strong><?= __('template', 'Payment Trace #: ')?></strong><?= $traceNumber ?></h4></p>
        </div>
        <?php foreach ($insurances as $insurance): ?>
        <div class="container my-5 row">
            <div class="col-7">
                <h3 class="mb-5"><?= __('insurance', 'Insurance Info') ?></h3>
                <table class="force-text-right">
                    <tr><th class="px-5 py-2"><?= __('insurance', 'Insured') ?></th><td class="px-5 py-2"><?= $insurance->customer->firstName ?> <?= $insurance->customer->lastName ?></td></tr>
                    <tr><th class="px-5 py-2"><?= __('insurance', 'Visa Type') ?></th><td class="px-5 py-2"><?= tools()->getOptionValue('Insurance', 'VisaType', $insurance->travelKind) ?></td></tr>
                    <tr><th class="px-5 py-2"><?= __('insurance', 'Insurance Serial No.') ?></th><td class="px-5 py-2"><?= $insurance->bimehNo ?></td></tr>
                    <tr><th class="px-5 py-2"><?= __('insurance', 'Status') ?></th><td class="px-5 py-2"><?= tools()->getOptionValue('Insurance', 'Status', $insurance->status) ?></td></tr>
                    <tr><th class="px-5 py-2"><?= __('insurance', 'Policy No.') ?></th><td class="px-5 py-2"><?= $insurance->policyNo ?></td></tr>
                    <tr><th class="px-5 py-2"><?= __('insurance', 'Passport No.') ?></th><td class="px-5 py-2"><?= $insurance->passportNo ?></td></tr>
                    <tr><th class="px-5 py-2"><?= __('insurance', 'Issue Date') ?></th><td class="px-5 py-2 ltr"><?= tools()->getFormatedDate($insurance->issueDate, 'Y-m-d H:i') ?></td></tr>
                    <tr><th class="px-5 py-2"><?= __('insurance', 'Duration of Stay') ?></th><td class="px-5 py-2"><?= $insurance->durationOfStay ?></td></tr>
                    <?php /*<tr><th class="px-5 py-2"><?= __('insurance', 'Agent Code') ?></th><td class="px-5 py-2"><?= $insurance->agentCode ?></td></tr>
                    <tr><th class="px-5 py-2"><?= __('insurance', 'Cancelation Date') ?></th><td class="px-5 py-2"><?= $insurance->cancelDate ?? __('insurance', 'Not Canceled') ?></td></tr>*/ ?>
                </table>
            </div>
            <div class="col-5 text-center files">
                <h3 class="mb-5"><?= __('insurance', 'Your Insurance PDF File') ?></h3>
                <object class="insurance-pdf" type="application/pdf" data="<?= $insurance->pdfPolicy ?>">
                    <p>Insert your error message here, if the PDF cannot be displayed.</p>
                </object>
                <div class="btn-wrapper">
                <button id="confirm_insurance" class="btn btn-primary">
                    <a href="<?= $insurance->pdfPolicy ?>" download target="_blank"><?= __('insurance', 'Download PDF') ?></a>
                </button>
                </div>
            </div>
        </div>
        <hr/>
        <?php endforeach ?>

        <div class="mt-5 mr-5">
            <button id="confirm_insurance" class="btn btn-primary">
                <a href="<?= tools()->getMediaUrl('insurance/saman/CoveredItems.pdf'); ?>" target="_blank"><?= __('insurance', 'Covered Items') ?></a>
            </button>
            <button id="confirm_insurance" class="btn btn-primary ml-3">
                <a href="<?= tools()->getMediaUrl('insurance/saman/PublicConditions.pdf'); ?>" target="_blank"><?= __('insurance', 'Public Conditions') ?></a>
            </button>
        </div>
    </div>
</section>
<hr>
