<div class="home3"></div>
<section class="term-policy_area mt-5 " style="color:#000;">
            <div class="container">

                
<!--Accordion wrapper-->
<div class="accordion md-accordion" id="accordionEx" role="tablist" aria-multiselectable="true">

  <!-- Accordion card -->
  <div class="card">

    <!-- Card header -->
    <div class="card-header" role="tab" id="headingOne1">
      <a data-toggle="collapse" data-parent="#accordionEx" href="#collapseOne1" aria-expanded="true"
        aria-controls="collapseOne1">
        <h5 class="mb-0 "><i class="fa fa-angle-up rotate-icon orange"></i>
         قوانین کلی
        </h5>
      </a>
    </div>

    <!-- Card body -->
    <div id="collapseOne1" class="collapse show" role="tabpanel" aria-labelledby="headingOne1" data-parent="#accordionEx">
      <div class="card-body">
       <ol class="col-12 mt-2">
                        <li class="mb-3">بلیت‌دات‌کام تابع قوانین جمهوری اسلامی ایران، جرایم اینترنتی و قوانین و مقررات تجارت الکترونیکی است.</li>
                        <li class="mb-3">محتوا و خدماتی که از سوی بلیت‌دات‌کام در اختیار کاربران قرار می‌گیرد متعلق به وب‌سایت بلیت‌دات‌کام است و هرگونه استفاده از مطالب و عکس‌ها فقط با ذکر نام و لوگوی وب‌سایت بلیت‌دات‌کام امکان پذیر است.</li>
                        <li class="mb-3">برای اطمینان هرچه بیش‌تر کاربران تمام اطلاعات شخصی آن‌ها در وب‌سایت بلیت‌دات‌کام کاملا محرمانه محافظت می‌شود.</li>
                        <li class="mb-3">فقط مشتری حق دارد که رمز عبور و نام کاربری برای خودش در وب‌سایت ایجاد کند. مسئولیت محافظت و نگه‌داری از نام کاربری و رمز عبور بر عهده خود مشتری است.</li>
                        <li class="mb-3">کاربران باید متعهد شوند که مشخصات خود را هنگام ثبت‌نام و خرید بلیت به صورت صحیح در وب‌سایت وارد کنند. بلیت‌دات‌کام هیچ‌گونه مسئولیتی در قبال اطلاعات نادرست کاربران ندارد.</li>
                    </ol>
      </div>
    </div>

  </div>
  <!-- Accordion card -->

  <!-- Accordion card -->
  <div class="card mt-4">

    <!-- Card header -->
    <div class="card-header" role="tab" id="headingTwo2">
      <a class="collapsed" data-toggle="collapse" data-parent="#accordionEx" href="#collapseTwo2"
        aria-expanded="false" aria-controls="collapseTwo2">
        <h5 class="mb-0"><i class="fa fa-angle-down rotate-icon orange"></i>
         قوانین اتوبوس 
        </h5>
      </a>
    </div>

    <!-- Card body -->
    <div id="collapseTwo2" class="collapse" role="tabpanel" aria-labelledby="headingTwo2" data-parent="#accordionEx">
      <div class="card-body">
        <ol class="col-12 mt-2">
                        <li class="mb-3"> جزییات بلیت اتوبوس در سایت بلیت‌دات‌کام شامل قیمت، نوع اتوبوس، ساعت و تاریخ حرکت، از سوی شرکت‌های مسافربری تعریف می‌شوند و بلیت‌دات‌کام در قابل هرگونه تغییر هیچ مسئولیتی ندارد.</li>
                        <li class="mb-3">_ بلیت‌دات‌کام هیچ‌گونه دخل و تصرفی در قیمت بلیت‌ها ندارد و قیمت‌ها بوسیله شرکت‌های مسافربری ثبت می‌گردد. </li>
                        <li class="mb-3"> قوانین و شرایط مربوط به بلیت‌ کاغذی (خرید غیر حضوری از ترمینال مسافربری) شامل بلیت‌های اینترنتی نیز می‌شود بنابراین هیچ تفاوتی میان بلیت کاغذی و بلیت اینترنتی وجود ندارد.</li>
                        <li class="mb-3">پس از صدور بلیت هیچ تغییری در تاریخ و ساعت حرکت، مبدا و مقصد، نوع اتوبوس امکان‌پذیر نیست. برای اعمال هرگونه تغییری بلیت باید از گزینه استرداد استفاده کنید.</li>
                        <li class="mb-3">اطلاعات خرید از طریق پیام کوتاه و پست الکترونیک ارسال می‌گردد.</li>
                        <li class="mb-3">خریدار موظف است به هنگام رزرو بلیت مشخصات خود را درست و صحیح وارد نماید.</li>
                        <li class="mb-3">توجه داشته باشید که باید حتما شماره بلیت را از سامانه مورد نظر دریافت کنید در غیر این صورت خرید شما کامل نخواهد شد.</li>
                        <li class="mb-3">حتما 30 دقیقه قبل از حرکت اتوبوس در پایانه مسافربری حضور داشته باشید تا بتوانید پرینت بلیت‌تان را تهیه کنید. </li>
                    </ol>
      </div>
    </div>

  </div>
  <!-- Accordion card -->

  <!-- Accordion card -->
  <div class="card mt-4">
      <!-- Card header -->
    <div class="card-header" role="tab" id="headingThree3">
      <a class="collapsed" data-toggle="collapse" data-parent="#accordionEx" href="#collapseThree3"
        aria-expanded="false" aria-controls="collapseThree3">
        <h5 class="mb-0"><i class="fa fa-angle-down rotate-icon orange"></i>
          قوانین بیمه 
        </h5>
      </a>
    </div>

    <!-- Card body -->
    <div id="collapseThree3" class="collapse" role="tabpanel" aria-labelledby="headingThree3" data-parent="#accordionEx">
      <div class="card-body">
  
      </div>
    </div>

  </div>
  <!-- Accordion card -->

</div>
<!-- Accordion wrapper -->
            </div>

        </section>
        