<div class="cta">
    <div class="cta_background parallax-window">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="cta_content">
                        <h3><?= __('template', 'To more comfort') ?></h3>
                        <h2><?= __('template', 'Application') ?></h2>
                        <h2><?= __('template', 'Bilit.com') ?></h2>

                        <div class="button cta_button"><a href="#"><?= __('template', 'Request a Plan') ?></a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
