<section class="section-full-small mt-5 align-items-center d-flex">
	<div class="container">
		<div class="row">
			<div class="col-lg-4 col-md-6  ">
				<div class="package  ">
					<span class="fa fa-map-marker  fz-20  ml-0 mr-2 orang"></span><span class="text-white fz-14 "><?= __('template', 'No 204, Aras Building, Second Shahnazi St. Madar Sq.') ?></span>
				</div>
			</div>
			<div class="col-lg-3 col-md-6 ">
				<div class="package text-center">
					<span class="fa fa-phone  fz-20  ml-0 mr-2 orang"></span><span class="text-white"><?= __('template', '021&nbsp;72149') ?> | <?= __('template', '0912&nbsp;2030&nbsp;153') ?></span>
				</div>
			</div>
			<div class="col-lg-2 col-md-6 ">
				<div class="package text-center ">
					<span class="fa fa-fax  fz-20  ml-0 mr-2 orang"></span><span class="text-white"><?= __('template', '021&nbsp;') ?></span>
				</div>
			</div>
			<div class="col-lg-3 col-md-6 ">
				<div class="package text-center">
					<span class="fa fa-envelope fz-20 ml-0 mr-2 orang"></span><span class="text-white"><?= __('template', 'info@bilit.com') ?></span>
				</div>
			</div>
		</div>
	</div>
</section>
