<section class="section-full">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 mt-2">
                <div class="single-pricing-table">
                    <div class="top">
                        <div class="head text-center">
                            <span class="fa fa-map-marker"></span><br>
                            <h5 class="text-white text-uppercase"><?= __('template', 'Address') ?></h5>
                        </div>
                        <div class="package text-center">
                            <div class="price"></div>
                            <span class="text-white"><?= __('template', 'No 204, Aras Building, Second Shahnazi St. Madar Sq.') ?></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mt-2">
                <div class="single-pricing-table">
                    <div class="top">
                        <div class="head text-center">
                            <span class="fa fa-phone"></span><br>
                            <h5 class="text-white text-uppercase"><?= __('template', 'Phone') ?></h5>
                        </div>
                        <div class="package text-center">
                            <div class="price"></div>
                            <span class="text-white"><?= __('template', '021&nbsp;72149') ?></span>
                            <br>
                            <span class="text-white"><?= __('template', '0912&nbsp;2030&nbsp;153') ?></span>
                        </div>
                    </div>
                </div>
            </div>
                <div class="col-lg-3 col-md-6 mt-2">
                <div class="single-pricing-table">
                    <div class="top">
                        <div class="head text-center">
                            <span class="fa fa-fax"></span><br>
                            <h5 class="text-white text-uppercase"><?= __('template', 'Fax') ?></h5>
                        </div>
                        <div class="package text-center">
                            <span class="text-white"><?= __('template', '021&nbsp;') ?></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mt-2">
                <div class="single-pricing-table">
                    <div class="top">
                        <div class="head text-center">
                            <span class="fa fa-envelope"></span>
                            <h5 class="text-white text-uppercase"><?= __('template', 'Email') ?></h5>
                        </div>
                        <div class="package text-center">
                            <div class="price"></div>
                            <span class="text-white"><?= __('template', 'info@bilit.com') ?></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>