<div class="copyright p-4">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="copyright_content text-center d-flex flex-lg-row flex-column align-items-lg-center justify-content-center">
                    <div class="cr">
                        Powered by <a href="https://www.creative-tim.com/" target="_blank">Creative Tim</a> Template | Made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://omidb.me/" target="_blank">CODNITIVE</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
