<div class="copyright">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="copyright_content text-center d-flex flex-lg-row flex-column align-items-lg-center justify-content-center">
                    <div class="cr">
                        Copyright &copy;
                        <script>
                            document.write(new Date().getFullYear());
                        </script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://nugig.com" target="_blank">NUGIG</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
