
          <div class="col-md-3">
            <ul class="nav">
              <li class="nav-item">
                <a href="<?= tools()->getUrl(); ?>" class="nav-link">
                  <?= __('template', 'Home') ?>
                </a>
              </li>
              <li class="nav-item">
                <a href="<?= tools()->getUrl('poker/game/start'); ?>" class="nav-link">
                  <?= __('template', 'Poker Chance Game') ?>
                </a>
              </li>
              <li class="nav-item">
                <a href="<?= tools()->getUrl('graph/analyze/form'); ?>" class="nav-link">
                  <?= __('template', 'String Graph') ?>
                </a>
              </li>
            </ul>
          </div>
          <div class="col-md-3">
            <ul class="nav">
              <li class="nav-item">
                <a href="https://www.omidb.me#section10" class="nav-link">
                  <?= __('template', 'Contact Me') ?>
                </a>
              </li>
              <li class="nav-item">
                <a href="https://omidb.me/" class="nav-link">
                  <?= __('template', 'About Me') ?>
                </a>
              </li>
              <li class="nav-item">
                <a href="https://cooode.run/" class="nav-link">
                  <?= __('template', 'Codnitive') ?>
                </a>
              </li>
            </ul>
          </div>