
        <div class="col-md-3">
            <h3 class="title"><?= __('template', 'Follow Me') ?></h3>
            <div class="btn-wrapper profile">
              <a target="_blank" href="https://github.omidb.me/" class="btn btn-icon btn-neutral btn-round btn-simple" data-toggle="tooltip" data-original-title="Follow My Projects">
                <i class="fab fa-github"></i>
              </a>
              <a target="_blank" href="https://linkedin.omidb.me/" class="btn btn-icon btn-neutral btn-round btn-simple" data-toggle="tooltip" data-original-title="Like Me">
                <i class="fab fa-linkedin"></i>
              </a>
            </div>
        </div>
            