<div class="passengers-supervisor-wrapper" <?php if (!empty($model->national_id)) echo 'style="display:none;"' ?>>
    <div class="d-flex flex-row flex-lg-row flex-md-row flex-sm-row align-items-center justify-content-between flex-column p-3">
        <h5 class="d-flex">
            <i class="fa fa-info-circle pink mr-2 ml-0"></i>
            <?= __('insurance', 'Please enter supervisor information.') ?>
        </h5>
        <?php /*
        <div class="d-flex ">
            <button type="button" data-toggle="modal" data-target="#box-history-modal" class="  btn submit_btn2 ">
                <i class="fa fa-user blue-i mr-2 ml-0 color-i"></i><?= __('template', 'Passenger Book') ?>
            </button>
        </div>*/ ?>
    </div>

    <div class="passengers-info">
        <?php $block->html()->setIndex(0); ?>
        <?= $this->render('form/passenger.form.phtml', [
            'model'       => $model,
            'block'       => $block,
            'form'        => $form,
            'class'       => 'supervisor',
            'cloneSample' => true,
            'showOptionals' => true
        ]) ?>

        <div class="passengers wrapper place-holder"></div>
    </div>
</div>
<?= $this->render('form/passengers-list.phtml', ['passengers' => $passengers]); ?>
<?php unset($passengers[0]) ?>
<div class="submitted-passengers-placeholder hidden">
    <?php foreach ($passengers as $index => $passenger): ?>
        <?php $block->html()->setIndex($index); ?>
        <?php $model->setAttributes($passenger) ?>
        <?= $this->render('form/passenger.form.phtml', [
            'model'       => $model,
            'block'       => $block,
            'form'        => $form,
            'class'       => '',
            'cloneSample' => true,
            'showOptionals' => false
        ]) ?>
    <?php endforeach; ?>
</div>

<?= $this->render('form/passengers.phtml'); ?>

<div class="info-box clearfix mt-3">
    <hr>
    <a href="<?= $block->getBackUrl() ?>" class="col-sm-2 col-xs-12 float-left back-link force-color-default"><?= __('template', 'Back') ?></a>
</div>
