<div class="about">
    <div class="container">
        <div class="row row-lg-eq-height">
            <div class="col">
                <div class="text-center mb-3">
                    <h2 class=""><img src="<?= tools()->getImageUrl('logo_blue.svg') ?>" alt="Bilit.com" style="width: 150px; height: 150px;"></h2>
                </div>
            </div>
            <div class="about-text  mb-3">
                <p >فروش آنلاین بلیت اتوبوس مهم‌ترین قسمت سایت بلیت‌دات‌کام است که جزو اولین الویت‌های راه‌اندازی سایت بوده. سفر با اتوبوس در گروه سفرهای زمینی و ارزان تقسیم‌بندی می‌شود و برخلاف تاثیر نواسانات تغییر قیمت‌ها بر بلیط هواپیما و قطار، بلیط اتوبوس با کم‌ترین تغییر در قیمت مواجه است. سفر با اتوبوس تجربه منحصر به فردی است که می‌تواند لذت سفر را دو چندان کند. سفر با اتوبوس یعنی ارتباط برقرار کردن با مسیر به همین دلیل می‌تواند خاطرات متفاوت و هیجان‌انگیزی به همراه داشته باشد. 
بلیت‌دات‌کام با پوشش تمام مسیرها سعی کرده دغدغه مسافران را برای خرید بلیت اتوبوس کاهش دهد.</p>
            </div>
        </div>
    </div>
</div>

<section class="benefit_area ">
    <div class="container">
        <div class="row  text-center d-flex flex-row align-items-center justify-content-around">
            <div class="col-md-3 col-sm-6 service_col d-flex justify-content-around ">
                <div class="service text-center trans_200">
                    <div class="service_icon flex-fill d-flex align-items-center justify-content-center
                    "><span class="icon-ticket color"></span></div>
                    <div class="service_title trans_200">جستجوی بلیط</div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 service_col">
                <div class="service text-center trans_200">
                    <div class="service_icon flex-fill d-flex align-items-center justify-content-center"><span class="icon-ticket-select color"></span></div>
                    <div class="service_title trans_200">انتخاب بلیط</div>

                </div>
            </div>
            <div class="col-md-3 col-sm-6 service_col">
                <div class="service text-center trans_200">
                    <div class="service_icon flex-fill d-flex align-items-center justify-content-center"><span class="icon-information color"></span></div>
                    <div class="service_title trans_200">تکمیل مشخصات</div>

                </div>
            </div>
            <div class="col-md-3 col-sm-6 service_col">
                <div class="service text-center trans_200">
                    <div class="service_icon flex-fill d-flex align-items-center justify-content-center"><span class="fa fa-shopping-cart color"></span></div>
                    <div class="service_title trans_200">خرید و پرداخت</div>
            </div>
        </div>
    </div>
    </div>
</section>

<!--================Creative Feature Area =================-->
<section class="bus_feature_area py-5 mt-5">
    <div class="container">
    
        <div class="bus_feature p_100">
            <div class="row">
                <div class="col-lg-6">
                    <div class="d_feature_text">
                        <div class="main_title">
                            <h2>مزایای خرید آنلاین بلیت اتوبوس از بلیت‌دات‌کام</h2>
                        </div>
                    <ol class="bus-feature-item mt-5 ml-4 mr-0">
<li>پوشش سراسری تمام مسیرها</li>
<li>امکان مقایسه تعاونی‌های مختلف ناوگان‌های اتوبوسرانی</li>
<li>امکان مشاهده مسیرهای مختلف 
</li>
<li>امکان انتخاب دقیق زمان حرکت به صورت غیرحضوری</li>
<li>امکان مقایسه اتوبوس‌ها در مسیرهای یکسان</li>
<li>امکان انتخاب صندلی </li>
<li>امکان مشاهده صندلی خانم‌ها و آقایان</li>
<li>پرداخت آنلاین</li>
<li>استرداد بلیت</li>
</ol>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="d_feature_img">
                        <img src="<?= tools()->getImageUrl('Herault-Transport-rond-point-Carnon_free_format.jpg') ?>">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
