<?php
$block = new app\modules\Codnitive\Account\blocks\Layouts\Html\Navigation\Side;
$userIdentity = tools()->getUser()->identity;
?>
<div class="box-user">
    <div class="c-profile-box">
        <div class="c-profile-box__header">
            <a href="<?= tools()->getUrl('account') ?>">
                <div class="c-profile-box__avatar <?php echo $userIdentity->gender == 1 ? 'men' : 'women' ?> js-user-avatar"></div>
            </a>
        </div>
        <div class="c-profile-box__username">
            <span class="block-dis mt-2 mb-3"><?= $userIdentity->fullname ?></span><span class="color  mt-3 fz-14 email-uesr">
            <?= $userIdentity->email ?>
        </span></div>
        <div class="c-profile-box__tabs d-flex ">
            <a href="<?= tools()->getUrl('account/user/settings', ['action' => 'change-password']) ?>" class="c-profile-box__tab c-profile-box__tab--access p-3 ">
                <i class="fa fa-lock"></i><?= __('account', 'Change Password') ?>
            </a>
            <a href="<?= tools()->getUrl('user/logout'); ?>" class="c-profile-box__tab c-profile-box__tab--sign-out p-3">
                <i class="fas fa-sign-out-alt"></i><?= __('account', 'Logout') ?>
            </a>
        </div>
    </div>
</div>
<div class="list-group d-flex flex-column justify-content-start ">
    <?php foreach ($block->getMenus() as $menuKey => $menu): ?>
    <a href="<?= tools()->getUrl($menu['route'], $menu['params'] ?? []) ?>" class="<?= isset($this->params['active_menu']) && $menuKey == $this->params['active_menu'] ? 'active ' : '' ?> list-group-item list-group-item-action d-flex justify-content-strat align-items-center">
        <i class="<?= $menu['icon'] ?>"></i><span class="ml-2 mr-0 align-self-end"><?= __('account', $menu['title']) ?></span>
    </a>
    <?php endforeach ?>
</div>
