<?php
$block = new app\modules\Codnitive\Account\blocks\Settings;
use yii\widgets\ActiveForm;
use app\modules\Codnitive\Core\helpers\Html;
use app\modules\Codnitive\Core\helpers\Tools;

Html::$nameSpace = 'settings-form';
?>

<div class="no-padding align-items-stretch box-center col-6">
    <?php $form = ActiveForm::begin([
        'id' => 'account-form',
        'options' => ['class' => 'form-horizontal col-12 flex-row row', 'autocomplete' => 'off'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-9\">{input}</div>\n<div class=\"col-sm-offset-3 col-lg-9\">{error}\n{hint}</div>",
            'labelOptions' => ['class' => 'col-lg-3 control-label'],
        ],
        'enableAjaxValidation' => true,
        'enableClientValidation' => false,
    ]); ?>
    <?= Html::getField($form, $model, 'new_password', '', '', ['form_group_class' => 'box-input col-12 mb-4 d-flex flex-column', 'class' => 'd-flex justify-content-start', 'force_form_group_class' => true])->passwordInput() ?>
    <?= Html::getField($form, $model, 'current_password', '', '', ['form_group_class' => 'box-input col-12 mb-4 d-flex flex-column', 'class' => 'd-flex justify-content-start', 'force_form_group_class' => true])->passwordInput() ?>
    <div class="box-input col-12 text-center d-flex flex-row justify-content-center">
        <?= Html::submitButton(__('account', 'Save'), ['class' => 'btn-blue col-6']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>
