<?php
$block = new app\modules\Codnitive\Account\blocks\Settings;
use yii\widgets\ActiveForm;
use app\modules\Codnitive\Core\helpers\Html;
use app\modules\Codnitive\Core\helpers\Tools;

Html::$nameSpace = 'settings-form';
?>

<?php $form = ActiveForm::begin([
    'id' => 'account-form',
    'options' => ['class' => 'form-horizontal col-12 flex-row row', 'autocomplete' => 'off'],
    'fieldConfig' => [
        'template' => "{label}\n<div class=\"col-lg-9\">{input}</div>\n<div class=\"col-sm-offset-3 col-lg-9\">{error}\n{hint}</div>",
        'labelOptions' => ['class' => 'col-lg-3 control-label'],
    ],
    'enableAjaxValidation' => true,
    'enableClientValidation' => false,
]); ?>
<?= Html::getField($form, $model, 'email', '', '', ['form_group_class' => 'box-input col-6 mb-4 d-flex flex-column', 'class' => 'd-flex justify-content-start', 'force_form_group_class' => true]); ?>
<?= Html::getField($form, $model, 'username', '', '', ['form_group_class' => 'box-input col-6 mb-4 d-flex flex-column', 'class' => 'd-flex justify-content-start', 'force_form_group_class' => true]) ?>
<?= Html::getField($form, $model, 'fullname', '', '', ['form_group_class' => 'box-input col-6 mb-4 d-flex flex-column', 'class' => 'd-flex justify-content-start', 'force_form_group_class' => true])->label(__('account', 'Full Name')) ?>
<?= Html::getDateField($form, $model, 'dob', $this, [
        'class'=> 'd-flex justify-content-start',
        'form_group_class' => 'box-input col-6 mb-4 d-flex flex-column',
        /*'form_group_class'  => 'col-12',*/
        // 'col_size'          => 'col-4',
        // 'remove_label' => true,
        // 'icon' => 'fa fa-calendar',
        // @reference datepicker page: https://github.com/Mds92/MD.BootstrapPersianDateTimePicker
        'date_options' => [
            // 'targetDateSelector' => '#bus-departing',
            // 'targetTextSelector' => '#bus-departing',
            'dateFormat' => 'yyyy-MM-dd',
            'textFormat' => 'yyyy-MM-dd',
            // 'isGregorian' => false,
            // 'disableBeforeToday' => true,
            'disableAfterToday' => true,
            // 'monthsToShow' => [0, 1],
            // 'rangeSelector' => true,
            'englishNumber' => true,
            'yearOffset' => 100,
            // 'rangeSelector' => false
        ]
    ])
    ->label(__('account', 'Birthday')) 
?>
<?= Html::getDropdownList(
        $form, 
        $model, 
        'gender', 
        tools()->genderOptions(),
        [
            'class'=> 'd-flex justify-content-start',
            'form_group_class' => 'box-input col-6 mb-4 d-flex flex-column',
            'prompt' => false,
            'live_search' => 'false'
        ],
        $this
    )
    ->label(__('account', 'Gender'))
?>
<?= Html::getField($form, $model, 'current_password', '', '', ['form_group_class' => 'box-input col-6 mb-4 d-flex flex-column', 'class' => 'd-flex justify-content-start', 'force_form_group_class' => true])->passwordInput() ?>
<div class="box-input col-12 text-center d-flex flex-row justify-content-center">
    <?= Html::submitButton(__('account', 'Save'), ['class' => 'btn-blue col-3']) ?>
</div>
<?php ActiveForm::end(); ?>
