<hr />
<div class="d-flex justify-content-between mt-5 mb-5">
  <div class="d-flex flex-column align-items-between">
    <h4 class="d-flex">
      <i class="fa fa-info-circle pink ml-2"></i><?= __('insurance', 'Other Passengers') ?>
    </h4>
    <h5 class="d-flex ml-2">
      <?= __('insurance', 'You can enter other passengers info here.') ?>
    </h5>
  </div>
  <div class="d-flex flex-column align-items-between">
    <div class="d-flex justify-content-end ">
      <a
        class="btn submit_btn2 col-xs-3 add-passenger"
        data-toggle="modal"
        data-target="#addModalCenter"
      >
      <?= __('insurance', 'Add New Passenger') ?>
    </a>
    </div>
  </div>
</div>

<!-- add-passenger-modal -->
<div
  class="p-3 add-pass-info modal fade"
  id="addModalCenter"
  tabindex="-1"
  role="dialog"
  aria-labelledby="exampleModalCenterTitle"
  aria-hidden="true"
  data-backdrop="static" 
  data-keyboard="false"
>
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title purple" id="exampleModalLongTitle">
          <?= __('insurance', 'Add New Passenger') ?>
        </h5>
        <?php /*<button
          type="button"
          class="close"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>*/ ?>
      </div>
      <div class="modal-body"></div>
      <div class="modal-footer d-flex justify-content-between">
        <button
          type="button"
          class="btn btn-secondary pull-left close-new-passenger"
          data-dismiss="modal"
        >
          <?= __('insurance', 'Close') ?>
        </button>
        <button type="button" class="btn bg-purple submit-new-passenger"><?= __('insurance', 'Add Passenger') ?></button>
      </div>
    </div>
  </div>
</div>
