<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\modules\Codnitive\Setup\models\Database */

$index = $block->html()->getIndex();

$fieldSetId = "passenger-{$index}";
$namespace  = 'insurance_registration';
$block->html()->setNameSpace($namespace);
$model->removed = 0;

?>
<div class="p-2 passenger-form-fields-wrapper <?= $class ?>" id="<?= $fieldSetId ?>" data-index="<?= $index ?>">
        <?= $block->html()->getHiddenField($form, $model, "removed[$index]"); ?>
    <div class="main-fields-wrapper row">
        <?= $block->html()->getField($form, $model, "national_id[$index]", '', '', ['form_group_class' => 'col-sm-6 col-md-4', 'class' => 'national-id ltr-field']); ?>
        <?= $block->html()->getField($form, $model, "persian_name[$index]", '', '', ['form_group_class' => 'col-sm-6 col-md-4', 'class' => 'persian-name']); ?>
        <?= $block->html()->getField($form, $model, "persian_lastname[$index]", '', '', ['form_group_class' => 'col-sm-6 col-md-4', 'class' => 'persian-lastname']); ?>
    </div>
    <div class="extra-fields-wrapper row" <?php if (empty($model->national_id)) echo 'style="display:none;"' ?>>
        <?= $block->html()->getField($form, $model, "passport_no[$index]", '', '', ['form_group_class' => 'col-sm-6 col-md-4', 'class' => 'passport-no ltr-field']); ?>
        <?= $block->html()->getField($form, $model, "english_name[$index]", '', '', ['form_group_class' => 'col-sm-6 col-md-4', 'class' => 'english-name ltr-field']); ?>
        <?= $block->html()->getField($form, $model, "english_lastname[$index]", '', '', ['form_group_class' => 'col-sm-6 col-md-4', 'class' => 'english-lastname ltr-field']); ?>
        <?= $block->html()->getDropdownList($form, $model, "gender[$index]", tools()->getOptionsArray('Insurance', 'Gender'), 
            ['form_group_class' => 'col-sm-6 col-md-4', 'class' => 'gender', 'prompt' => __('insurance', 'Gender'), 'live_search' => 'false'], $this) ?>
        <?= $block->html()->getDropdownList($form, $model, "visa_type[$index]", tools()->getOptionsArray('Insurance', 'VisaType'), 
            ['form_group_class' => 'col-sm-6 col-md-4', 'class' => 'visa-type', 'prompt' => __('insurance', 'Visa Type'), 'live_search' => 'false'], $this) ?>
        

        <?= $block->html()->getHiddenField($form, $model, "birthday[$index]"); ?>
        <?= $block->html()->getDateField($form, $model, "birthday_persian[$index]", $this, [
                'class'=> 'birthday-datepicker birthday',
                'form_group_class' => 'col-sm-6 col-md-4',
                /*'form_group_class'  => 'col-12',
                'col_size'          => 'col-12',*/
                // 'remove_label' => false,
                'icon' => '',
                // @reference datepicker page: https://github.com/Mds92/MD.BootstrapPersianDateTimePicker
                'date_options' => [
                    'targetDateSelector' => "#insurance_registration-birthday-$index",
                    // 'targetTextSelector' => '#bus-departing',
                    'dateFormat' => 'yyyy-MM-dd',
                    // 'textFormat' => 'yyyy-MM-dd',
                    // 'isGregorian' => false,
                    // 'disableBeforeToday' => true,
                    'disableAfterToday' => true,
                    // 'monthsToShow' => [0, 1],
                    // 'rangeSelector' => true,
                    'englishNumber' => true,
                    'yearOffset' => 100,
                    // 'rangeSelector' => false
                ]
            ])
            ->label(__('insurance', 'Birthday')) 
        ?>
        

        <?php if ($showOptionals): ?>
            <?= $block->html()->getField($form, $model, "cellphone[$index]", '', '', ['form_group_class' => 'col-sm-6 col-md-4', 'class' => 'cell-phone']); ?>
            <?= $block->html()->getField($form, $model, "email[$index]", '', '', ['form_group_class' => 'col-sm-6 col-md-4', 'class' => 'email']); ?>
        <?php endif; ?>
        <script>
            $(document).ready(function () {
                $('.selectpicker').selectpicker()
            });
        </script>
    </div>
</div>
