<div class="col-xs-12 section-of-confirm-info confirm-applicant-info passengers-list" <?php if (empty($passengers)) echo 'style="display:none;"' ?>>
    <h4 class="head-of-info-ticket"><i class="fas fa-ticket-alt"></i> <span><?= __('insurance', 'Passengers') ?></span></h4>
    <hr>
    <div class="parent-table-confirm-info table-responsive passengers-list-table">
        <table class="table style-table">
            <thead class="force-color-default">
                <tr>
                    <th></th>
                    <th><?= __('insurance', 'Name') ?></th>
                    <th><?= __('insurance', 'English Name') ?></th>
                    <th><?= __('insurance', 'National ID') ?></th>
                    <th><?= __('insurance', 'Passport No.') ?></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr class="hidden">
                    <td class="index"></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <?php $i = 1 ?>
                <?php foreach ($passengers as $index => $passenger): ?>
                <tr id="passenger-<?= $index ?>_row" data-index="<?= $index ?>">
                    <td class="index"><?= $i++ ?></td>
                    <td><?= $passenger['persian_name'] ?> <?= $passenger['persian_lastname'] ?></td>
                    <td><?= $passenger['english_name'] ?> <?= $passenger['english_lastname'] ?></td>
                    <td><?= $passenger['national_id'] ?></td>
                    <td><?= $passenger['passport_no'] ?></td>
                    <td class="action">
                        <a href="javascript:;" class="mx-1 edit-passenger" title="ویرایش" data-index="<?= $index ?>"><i class="fa fa-edit"></i></a>
                        <?php if ($index > 0): ?>
                        <a href="javascript:;" class="mx-1 remove-passenger" title="حذف" data-index="<?= $index ?>"><i class="fa fa-trash"></i></a>
                        <?php endif ?>
                    </td>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>
