<?php //$block = new \app\modules\Codnitive\Core\blocks\Template ?>
<?php 
    $block = new \app\modules\Codnitive\Bus\blocks\Process\Registration;
    // $block->registerAssets($this, 'Insurance', 'Insurance');
    $block->html()->setNameSpace('bus_registration');
?>
<div class="home2"></div>
<?= $breadcrumbs ?>

<div class="bus-check container mb-4 mt-2" id="scroller-anchor-main">
    <?php $form = $block->beginForm([
        'action' => tools()->getUrl('bus/process/confirm'),
        'options' => [
            'method' => 'post',
            'id' => 'bus_registration_form'
        ]
    ]); ?>
        <div class="d-flex flex-column ">
            <div class="d-flex flex-row">
                <div class="col-md-9 pd-right">
                    <div class="d-flex flex-column">
                        <div class="box-shadow">
                            <?php if (tools()->isGuest()): ?>
                            <?= $this->render('@app/modules/Codnitive/Template/views/templates/quick_login.phtml') ?>
                            <?php endif; ?>
                            <div class="p-3">
                                <?= $this->render('/templates/process/registration/form.phtml', [
                                    'model' => $model, 
                                    'form' => $form,
                                    'passengersCount' => $passengersCount,
                                    'block' => $block
                                ]) ?>
                            </div>
                        </div>
                    </div>
                </div>
                <?= $this->render('/templates/process/sidebar.phtml', [
                    'step' => 'registration', 
                    'model' => $model, 
                    'form' => $form,
                    'data' => $bus
                ]) ?>
            </div>
        </div>
    <?php $block->endForm(); ?>
</div>
