<?php $block = new \app\modules\Codnitive\Bus\blocks\Process\Confirm($data); ?>
<div class="box-shadow col-md-3 px-3 py-2 align-self-start sidebar sticky-box">
    <div class="d-flex flex-column justify-content-center ">
        <ul class="sidebar-item-car">
            <?php if ($step == 'confirm'): ?>
            <li class="my-2">
                <span class="gray d-block mb-1">
                    <i class="fa fa-bus mr-2 ml-0 color"></i> <span><?= __('bus', 'Company') ?></span>
                </span>
                <p class="mb-2"><?= $data['reservation']['company'] ?></p>
            </li>
            <?php endif ?>
            <li class="my-2">
                <span class="gray d-block mb-1">
                    <i class="fa fa-home mr-2 ml-0 color"></i> <span><?= __('bus', 'Origin') ?></span>
                </span>
                <p class="mb-2"><?= $data['origin_name'] ?> - <?= $data['reservation']['boarding'] ?></p>
            </li>
            <li class="my-2">
                <span class="gray d-block mb-1">
                    <i class="fa fa-bus fz-10 mr-2 ml-0 color"></i> <span class="gray"><?= __('bus', 'Destination') ?></span>
                </span>
                <p class="mb-2"><?= $data['destination_name'] ?> - <?= $data['reservation']['dropping'] ?></p>
            </li>
            <li class="my-2">
                <span class="gray d-block mb-1">
                    <i class="fa fa-clock-o color mr-2 ml-0"></i><?= __('bus', 'Departure Date and Time') ?>
                </span>
                <p class="fw-medium mb-2">
                    <span class="mx-10" id="sidebar_FromDateTime">
                        <?= $block->getDate($data['reservation']['departure']) ?>&nbsp;<?= $block->getTime($data['reservation']['departure']) ?>
                    </span>
                </p>
            </li>
        </ul>
        <?php if ($step == 'registration'): ?>
        <div class="info-box__rules clearfix mt-3 terms-and-conditions">
            <div class="rule">
                <?php 
                    $termsLabel = __(
                        'bus', 
                        'I am agree with <a href="{terms}" target="_blank">all terms</a> and <a href="{bus_terms}" target="_blank">bus terms</a>.',
                        ['terms' => tools()->getUrl('terms-and-conditions'), 'bus_terms' => tools()->getUrl('terms-and-conditions', ['#' => 'collapseTwo2'])]
                        // ['terms' => tools()->getUrl('terms-and-conditions'), 'bus_terms' => tools()->getUrl('bus-terms-and-conditions')]
                    ) 
                ?>
                <?= $block->html()->getCheckboxList($form, $model, 'terms', [1 => '']) ?>
                <label for="bus_registration-terms-0" class="required"><?= $termsLabel ?></label>
            </div>
            <div class="d-flex f mb-3 col-12 mt-5">
                <?= $block->html()->submitButton(
                    __('bus', 'Continue Shopping'), 
                    [
                        'class' => 'btn btn-pink',
                        'id' => 'bus_registration_form_submit',
                    ]
                ) ?>
            </div>
        </div>
        <?php elseif ($step == 'confirm'): ?>
            <div class="sidebar-payment-methods-wrapper">
            <?= $this->render('sidebar/payment.phtml', ['block' => $block]) ?>
            </div>
        <?php endif ?>
    </div>
</div>
                