<div class="home2"></div>
<?= $breadcrumbs ?>

<div class="clearfix"></div>
<section class="mb-0 mt-2">
    <div class="container">
        <div class="text-center">
            <h2 class="my-5"><?= __('template', 'Thank you for your order!') ?></h2>
            <p><h4><strong><?= __('template', 'Order #: ') ?></strong><?= $ticket['order_number'] ?></h4></p>
            <p><h4><strong><?= __('template', 'Payment Trace #: ')?></strong><?= $ticket['payment_trace_number'] ?></h4></p>
        </div>
        <?php if (!empty($ticket) && !isset($ticket['continue_action'])): ?>
        <?= $this->render('/templates/ticket.phtml', ['ticket' => $ticket]) ?>
        <?php endif; ?>
    </div>
</section>
<hr>