      <div class="section section-javascript" id="projects_list">
        <div class="section container">
          <div class="row">
            <div class="title card-register col-lg-6 p-0 m-0">
              <div class="card-header">
                <img class="card-img" src="<?= tools()->getImageUrl('square1.png') ?>" alt="Card image">
                <h4 class="card-title"><?= __('template', 'Poker Chance') ?></h4>
              </div>
            </div>
            <div class="col-lg-5 mb-5 mb-lg-0 ">
              <h1 class="text-white font-weight-light">Poker game</h1>
              <p class="text-white mt-4">Web application should calculate chance of getting desired card based on the amount of cards left.
Use string notation to designate cards.</p>
              <a href="<?= tools()->getUrl('poker/game/start'); ?>" class="btn btn-warning mt-4"><?= __('template', 'Start Game') ?></a>
            </div>
          </div>
        </div>

        <div class="section container">
          <div class="row">
            <div class="title card-register col-lg-6 p-0 m-0">
              <div class="card-header">
                <img class="card-img" src="<?= tools()->getImageUrl('square1.png') ?>" alt="Card image">
                <h4 class="card-title"><?= __('template', 'String Graph') ?></h4>
              </div>
            </div>
            <div class="col-lg-5 mb-5 mb-lg-0 ">
              <h1 class="text-white font-weight-light">String analyzer</h1>
              <p class="text-white mt-4">Create a web application that will analyse customer input and provide some statistics.</p>
              <p class="text-white mt-4"></p>
              <a href="<?= tools()->getUrl(''); ?>" class="btn btn-warning mt-4"><?= __('template', 'Start Analyze') ?></a>
            </div>
          </div>
        </div>
      </div>
      

