      <div class="section section-javascript" id="javascriptComponents">
        <div class="section">
          <div class="container">
            <div class="title">
              <h3><?= __('template', 'Poker Chance') ?></h3>
            </div>
            <div class="row justify-content-between align-items-center">
              <div class="col-lg-5 mb-5 mb-lg-0 ">
                <h1 class="text-white font-weight-light">Poker game</h1>
                <p class="text-white mt-4">Web application should calculate chance of getting desired card based on the amount of cards left.
Use string notation to designate cards.</p>
                <a href="./docs/1.0/components/alerts.html" class="btn btn-warning mt-4"><?= __('template', 'Start Game') ?></a>
              </div>
              <div class="col-lg-6">
                <div id="carouselExampleControls" class="carousel slide">
                  <div class="carousel-inner">
                    <div class="carousel-item active">
                      <img class="d-block w-100" src="<?= tools()->getImageUrl('denys.jpg') ?>" alt="First slide">
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="section">
          <div class="container">
            <div class="title">
              <h3><?= __('template', 'String Graph') ?></h3>
            </div>
            <div class="row justify-content-between align-items-center">
              <div class="col-lg-6">
                <div id="carouselExampleControls" class="carousel slide">
                  <div class="carousel-inner">
                    <div class="carousel-item active">
                      <img class="d-block w-100" src="<?= tools()->getImageUrl('mark-finn.jpg') ?>" alt="First slide">
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-lg-5 mb-5 mb-lg-0 ">
                <h1 class="text-white font-weight-light">String analyzer</h1>
                <p class="text-white mt-4">Create a web application that will analyse customer input and provide some statistics.</p>
                <p class="text-white mt-4"></p>
                <a href="./docs/1.0/components/alerts.html" class="btn btn-warning mt-4"><?= __('template', 'Start Analyze') ?></a>
              </div>
            </div>
          </div>
        </div>
      </div>
      

