<!-- Logo -->
<div class="logo_container_outer">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="logo_container align-items-center">
                    <a href="<?= tools()->getUrl() ?>">
                        <img src="<?= tools()->getImageUrl('logo_white_pointer.svg'); ?>" alt="<?= __('template', 'Bilit Website') ?>">
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
