
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg fixed-top navbar-transparent " color-on-scroll="100">
    <div class="container">
      <div class="navbar-translate">
        <a class="navbar-brand" href="<?= tools()->getUrl() ?>" rel="tooltip" title="" data-placement="bottom">
          <span>Omid</span> Codnitive
        </a>
        <button class="navbar-toggler navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-bar bar1"></span>
          <span class="navbar-toggler-bar bar2"></span>
          <span class="navbar-toggler-bar bar3"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse justify-content-end" id="navigation">
        <div class="navbar-collapse-header">
          <div class="row">
            <div class="col-6 collapse-brand">
              <a>
                Omid
              </a>
            </div>
            <div class="col-6 collapse-close text-right">
              <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                <i class="tim-icons icon-simple-remove"></i>
              </button>
            </div>
          </div>
        </div>
        <ul class="navbar-nav">
          <li class="nav-item p-0">
            <a class="nav-link" rel="tooltip" title="" data-placement="bottom" href="https://github.omidb.me/" target="_blank">
              <i class="fab fa-linkedin"></i>
              <p class="d-lg-none d-xl-none">Linkedin</p>
            </a>
          </li>
          <li class="nav-item p-0">
            <a class="nav-link" rel="tooltip" title="" data-placement="bottom" href="https://linkedin.omidb.me/" target="_blank">
              <i class="fab fa-github-square"></i>
              <p class="d-lg-none d-xl-none">Github</p>
            </a>
          </li>
          <li class="dropdown nav-item">
            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
              <i class="fa fa-cogs d-lg-none d-xl-none"></i> Getting Started
            </a>
            <div class="dropdown-menu dropdown-with-icons">
              <a href="<?= tools()->getUrl('poker/game/start') ?>" class="dropdown-item">
                <i class="tim-icons icon-paper"></i> Poker Change
              </a>
              <a href="<?= tools()->getUrl('graph/analyze/form'); ?>" class="dropdown-item">
                <i class="tim-icons icon-bullet-list-67"></i>String Graph
              </a>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- End Navbar -->
