<?php
$data = $block->getData();
?>
<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 mt-5">
    <div id="accordion" class="panel panel-primary behclick-panel">
        <div class="panel-body">
            <div class="panel-heading ">
                <h4 class="panel-title">
                    <a data-toggle="collapse" href="#collapse0" aria-expanded="true">
                        <?= __('bus', 'Order Detail') ?><i class="indicator fa fa-caret-down" aria-hidden="true"></i>
                    </a>
                </h4>
            </div>
            
            <div id="collapse0" class="panel-collapse collapse show">
                <?= $this->render('_details.phtml', ['block' => $block, 'data' => $data]) ?>
            </div>
        </div>
    </div>
</div>
