<?php
$data = $block->getData();
?>
<div class="col-xs-12 section-of-confirm-info confirm-applicant-info ">
    <h4 class="head-of-info-ticket"><i class="fas fa-ticket-alt ml-0 mr-1 color"></i> <span><?= __('bus', 'Customer') ?></span></h4>
    <div class="parent-table-confirm-info table-responsive">
        <table class="table  style-table">
            <thead class="force-color-default">
            <tr>
                <th><?= __('bus', 'Supervisor') ?></th>
                <th><?= __('bus', 'Cell Phone') ?></th>
                <th><?= __('bus', 'Passengers Count') ?></th>
                <th><?= __('bus', 'Ticket Price') ?></th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td><?= $data['passenger_info']['firstname'] ?> <?= $data['passenger_info']['lastname'] ?></td>
                <td><?= $data['passenger_info']['cellphone'] ?></td>
                <td><?= $block->getSeatsCount() ?></td>
                <td><?= $block->getFinalPrice() ?></td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

<div class="info-box clearfix mt-3 p-3">
    <hr>
    <a href="<?= tools()->getUrl('bus/process/registration') ?>" class="col-sm-2 col-xs-12 float-left back-link force-color-default"><?= __('template', 'Back') ?></a>
</div>
