<?php
$data = $block->getData();
?>
<!-----------------right-section------------------------>
<div class="d-flex flex-column bus-item col-12 bus-confirm">
    <div class="clearfix seat-map bus-rows-<?= $rowsCount ?>">
        <div class="seats busBack"></div>
    </div>
</div>
<?php 
$seatMap = $block->getReviewSeatMap($seatMap, $seatNumbers);
?>

<script>
<?php 
/**
 * @reference https://www.jqueryscript.net/chart-graph/Full-featured-Seating-Chart-Plugin-With-jQuery-Seat-Charts.html
 * @reference https://github.com/mateuszmarkowski/jQuery-Seat-Charts
 */
?>
$(document).ready(function() {
    seatMap = $('.seat-map .seats').seatCharts({
        map: [
            <?php foreach ($seatMap as $col): ?>
                '<?= $col ?>',
            <?php endforeach; ?>
        ],
        seats: {
            r: {
                classes : 'reserved',
                category: 'Reserved'
            },
            u: {
                classes : 'unavailable',
                category: 'Booked'
            }
        },
        naming : {
            top : false,
            left: false,
            getLabel: function (character, row, column) {
                return null;
            }
        },
        legend : {
            node : $('.seat-map #legend'),
                items : [
                    [ 'r', 'reserved',   'Reserved'],
                    [ 'u', 'unavailable', 'Booked']
                ]         
        },
        click: function () {
            if (this.status() == 'available') {
                return 'unavailable';
            } 
            else if (this.status() == 'selected') {
                return 'unavailable';
            } 
            else if (this.status() == 'unavailable') {
                return 'unavailable';
            } 
            else {
                return this.style();
            }
        }
    });
    $('.seatCharts-row .reserved.available').click()
});
</script>
