<?php 
/**
 * Winner modal code
 *
 * @author Omid Barza <hbarza@gmail.com>
 */
?>

<!-- The Modal -->
<div class="modal" id="poker_modal_box" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Hooray, You Win!</h4>
      </div>

      <!-- Modal body -->
      <div class="modal-body text-center">
        <span data-notify="icon" class="tim-icons icon-trophy display-1 text-warning"></span>
        <div class="score-container score-primary">
            <div class="score d-block">
                <i class="fas fa-star p-1 star-1"></i>
                <i class="fas fa-star p-1 star-2"></i>
                <i class="fas fa-star p-1 star-3"></i>
                <i class="fas fa-star p-1 star-4"></i>
                <i class="fas fa-star p-1 star-5"></i>
            </div>
        </div>
        <div class="statistics my-3">
            <div class="message-wrapper display-4"></div>
            <div class="progress-container progress-primary">
                <div class="progress">
                    <div class="progress-bar progress-bar-warning" role="progressbar" 
                        aria-valuenow="0" 
                        aria-valuemin="0" 
                        aria-valuemax="100" 
                        style="width: 0%;">
                    </div>
                </div>
            </div>
        </div>
        <i class="card mx-2 my-4 d-inline-block icon icon-xl tim-icons display-1 text-center text-white"></i>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
          <a href="<?= tools()->getUrl('poker/game/start',) ?>" class="text-white btn btn-info">Play Again</a>
      </div>

    </div>
  </div>
</div>
