<section id="blog" class="section-full">
    <div class="container">
        <div class="container">
        <div class="box-sliders-title">
            <h4><?= __('template', 'Bilit.com Magazine') ?></h4> <a class="full-lists " href=""><?= __('template', 'View All') ?><i class="fa fa-left"></i></a>
            <div class="clear"></div>
        </div>
    </div>
        <div class="row mt-5">
            <div class="col-lg-3 col-md-6  mt-5">
                <div class="single-publish">
                    <img src="<?= tools()->getImageUrl('l-news-3.jpg') ?>" class="img-fluid" alt="">
                    <div class="top">
                        <div class="mb-15 d-flex">
                            <a href="#">25 فروردین, 1397</a>
                            <span class="line">|</span>
                            <a href="#">توسط ادمین</a>
                        </div>
                        <h6 class="text-uppercase h-60"><a href="#">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت</a></h6>
                    </div>
                    <p class="mb-30 h-80">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و </p>
                    <a href="#" class="details-btn d-flex justify-content-center align-items-center"><span class="details"><?= __('template', 'More') ?></span><span class="fas fa-arrow-left"></span></a>
                </div>
            </div>
        <div class="col-lg-3 col-md-6 mt-5">
                <div class="single-publish">
                    <img src="<?= tools()->getImageUrl('l-news-1.jpg') ?>" class="img-fluid" alt="">
                    <div class="top">
                        <div class="mb-15 d-flex">
                            <a href="#">05 آذر, 1397</a>
                            <span class="line">|</span>
                            <a href="#">By Mark Wiens</a>
                        </div>
                        <h6 class="text-uppercase h-60"><a href="#">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از </a></h6>
                    </div>
                    <p class="mb-30 h-80">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان های زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و   </p>
                    <a href="#" class="details-btn d-flex justify-content-center align-items-center"><span class="details"><?= __('template', 'More') ?></span><span class="fas fa-arrow-left"></span></a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mt-5">
                <div class="single-publish">
                    <img src="<?= tools()->getImageUrl('l-news-2.jpg') ?>" class="img-fluid" alt="">
                    <div class="top">
                        <div class="mb-15 d-flex">
                            <a href="#">14 اردیبهشت, 1397</a>
                            <span class="line">|</span>
                            <a href="#">By Mark Wiens</a>
                        </div>
                        <h6 class="text-uppercase h-60"><a href="#">لورم ایپسوم متن ساختگی با تولید سادگی </a></h6>
                    </div>
                    <p class="mb-30 h-80"> ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که   </p>
                    <a href="#" class="details-btn d-flex justify-content-center align-items-center"><span class="details"><?= __('template', 'More') ?></span><span class="fas fa-arrow-left"></span></a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mt-5">
                <div class="single-publish">
                    <img src="<?= tools()->getImageUrl('l-news-1.jpg') ?>" class="img-fluid" alt="">
                    <div class="top">
                        <div class="mb-15 d-flex">
                            <a href="#">05 آذر, 1397</a>
                            <span class="line">|</span>
                            <a href="#">By Mark Wiens</a>
                        </div>
                        <h6 class="text-uppercase h-60"><a href="#">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از </a></h6>
                    </div>
                    <p class="mb-30 h-80">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان های زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و   </p>
                    <a href="#" class="details-btn d-flex justify-content-center align-items-center"><span class="details"><?= __('template', 'More') ?></span><span class="fas fa-arrow-left"></span></a>
                </div>
            </div>
            
        </div>
        <div class="clearfix"></div>
    </div>
</section>
        