<?php

$block = new app\modules\Codnitive\Template\blocks\SearchForm;
// $block->registerAssets($this, 'Template', 'MDPersianDatepicker');
$forms = $block->getConfigs();
// $activeTab = 'box-bus';

?>

<!-- 3 Boxes -->
<div class="bilit-serach-box">
    <div class="boxes tabs d-flex justify-content-center">
        <ul class="flex-nowrap search d-flex justify-content-center justify-content-md-around tab-items">
            <?php foreach($forms as $index => $form): ?>
            <li class="flex-fill p-2 tab-<?= $index ?> tab-item" 
                id="<?= $form['name'] ?>" 
                data-tab-id="<?= $form['content_id'] ?>" 
                data-form="<?= $form['form'] ?>"
                data-color="<?= $form['color'] ?>">
                <div class="d-flex d-md-flex flex-md-row align-items-center justify-content-center item-search order-<?= $index ?> <?= $form['name'] ?>">
                    <span class="<?= $form['icon'] ?>"></span>
                </div>
                <div class="title <?= $form['title_class'] ?> <?= $form['color'] ?>" 
                    style="color: <?= $form['color_code'] ?>;">
                        <?= __('template', $form['title']) ?>
                </div>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <div class="tab-content">
        <div class="container tab-wrapper">
            <?php foreach($forms as $index => $form): ?>
            <div class="tab <?= $form['content_id'] ?> tab-<?= $index ?>" id="<?= $form['content_id'] ?>">
                <?= $this->render($form['template']) ?>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>
